--- 调用module函数,让其成为全局的 可以找到的模块
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LSC.
--- DateTime: 2020/7/2 17:40
---

module("Device",package.seeall);

---获取设备名称
function GetDeviceName()
    return "PC";
end

print("装载Device脚本");

