--- 赋值语句
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LSC.
--- DateTime: 2020/7/2 0:33
---
--赋值语句
local temp;
temp = 3;
temp = "HelloWorld";--temp这个变量存放字符对象的引用(temp指向字符对象)
temp = {--temp指向一个表对象temp这个变量里面存了这个对象的引用
    hello = 3,
}

function test_func()
    print("test_func:",temp);
end

test_func();

--字符串加法 ..
print("hello".."world".."aa");

--lua没有简化表达式(++ +=)

-- 条件判断
-- >,>=,<=,<,~=,==
if true then
    print("do if");
end

temp = 16;

if temp >= 15 then
    print("temp大");
else
    print("temp小");
end

--多个条件判断  and or
if true or false then
    print("zzz");
end

if true and false then
    print("sss");
end

--if elseif
temp = 20;
if temp > 50 then
    print("temp大于50");
elseif temp > 30 then
    print("temp大于30");
else
    print("temp小于30");
end

--for循环语句
--for 初始值,结束值,每次迭代的步长(可写可不写) do end
--[[

for i = 1,10 do--默认步长为1
	print("for遍历:" ,i);
end

for i = 1,10,2 do
	print("for 步长2遍历:" ,i);
end

for i = 10,1,-1 do
	print("for 步长-1遍历:",i);
end

--]]

--偶数的和
function EvenSum()
    local sum = 0;
    for tem = 2,100,2 do
        sum = sum + tem;
    end
    return sum;
end
print("0-100偶数求和:"..EvenSum());

--0-100的数之和
function HundredSum()
    local sum = 0;
    for i = 0,100 do
        sum = sum + i;
    end
    return sum;
end
print("0-100求和:"..HundredSum());

--while
i = 1;sum = 0;
while i <= 100 do
    sum = sum + i;
    i = i + 1;
end
print("while 0-100求和:"..sum);