---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LSC.
--- DateTime: 2020/7/2 17:34
---

local mathFunc = require("mathfunc");
local num = mathFunc.abs(-6666);
print("Main.lua 调用绝对值方法:"..num);

require("Device");
require("Test");
