--- 数学方法
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LSC.
--- DateTime: 2020/7/2 0:34
---
--绝对值
function math_abs(num)
    if num < 0 then
        return -num;
    end
    return num
end

--开根号
function math_sqrt(num)
    if num ~= 0 then
        return math.sqrt(num);
    end
end

local function privateFunc()
    print("this is a private function");
end

--函数分内部函数和接口函数
--如果是内部函数,需要加上local 不能在外部进行调用
--为了方便用户使用和管理  模块的接口函数,统一的导出来

print("装载mathfun.lua脚本");

local list = {
    abs = math_abs,
    sqrt = math_sqrt,
}

return list;