---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LSC.
--- DateTime: 2020/7/2 0:36
---
--多返回值
local function multiReturnFunc()
    return 66,"multi";
end

print(multiReturnFunc());

--unpack函数
local array_data = {2,3,4,5,6,7,8};
local one,two,three,four,five = unpack(array_data);
print(three,four);--4 5

--end

--lua虚拟机加载第一个lua脚本执行
--再由这个脚本去包含其他的脚本  代码模块

--require 来加载代码,不需要后缀名
--如果一个lua代码被require多次 require只会装载执行lua代码一次

--多次require只会装载和执行一次lua脚本,但是第二次require的时候
--发现前面已经require过了,所以直接返回第一次装载的返回值
local temp = require("mathfunc");
print("绝对值:"..math_abs(-66));