--- 字符串拼接
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LSC.
--- DateTime: 2020/7/2 0:36
---
--字符串拼接
local temp = "hello";
local item = "world";
--[[ 字符串拼接

--字符串和字符串拼接
print(temp..item);
--字符串和基本的数据相加
print(temp .. 8);


--数字转字符串
print(tostring(8.8));
print(type(tostring(8.8)));

--字符串转数字
temp = "6.6";
print(type(temp));
print(tonumber(temp));
print(type(tonumber(temp)));

--]]

--字符串长度
local str = "HelloWorld!!!";
print("长度:"..string.len(str));--13

--重复返回n次字符串
print("重复返回n次:"..string.rep("test",3));--testtesttest

--全部转成小写
print("转成小写:"..string.lower(str));--helloworld!!!

--全部转成大写
print("转成大写:"..string.upper(str));--HELLOWORLD!!!

--截取i到j之间的字符串 索引是从1开始,而不是0
print("截取字符串:"..string.sub(str,2,5));--ello j可写可不写,默认是-1,指向字符串的结尾

--格式化输入
print("格式化输入:"..string.format("%d-%d-%d",2020,7,7));--2020-7-7

--查找字符串位置
print("字符串的索引:"..string.find(str,"llo"));--3

--替换字符串
print("替换字符串:"..string.gsub(str,"l","ww"));--HewwwwoWorld!!!
print("替换字符串:"..string.gsub(str,"l","ww",1));--HewwloWorld!!! 替换次数可选.不写的话,默认是全部替换


