---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LSC.
--- DateTime: 2020/7/2 0:09
---
require("mathfunc");
local temp = math_abs(-14);
print(temp);

local mathFunc = require("mathfunc");
print("外部接口:"..mathFunc.abs(-666));

require("Device");

local deviceName = Device.GetDeviceName();
print(deviceName);